# frozen_string_literal: true

source "https://rubygems.org"
ruby 'ruby 2.4.1p111'
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'sinatra'
gem 'sinatra-reloader'
gem 'rspec'
gem 'rack'
gem 'rack-test'
gem 'sendgrid-ruby'
gem 'pry'
